model:
  num_encoders: 2
  num_decoders: 2
  pretrained_embedding: "efficientnet_b0"

  d_model: 256
  num_heads: 8
  dropout: 0.3

training:
  # Basic hyperparameters
  epochs: 150
  batch_size: 8
  lr: 1e-4
    
  # File path locations
  save_path: 'models'
  file_name: 'best2'
  load_path: ''
  diagram_path: ''
    
  # Weights used for joint loss
  recognition_weight: 1.0
  translation_weight: 1.0
  
  # Random splitting seed and ration
  seed: 29
  split: [0.8, 0.1, 0.1]

  # Early Stopping
  patience: 3
  delta: 0.01

  # Misc.
  num_workers: 0
  num_frames: 60

testing:
  load_path: 'models/best.pt'
  beam_search: false