model:
  num_encoders: 2
  num_decoders: 2

  d_model: 512
  num_heads: 8
  dropout: 0.3

training:
  epochs: 30
  save_path: 'models'
  load_path: ''

  num_frames: 60
  seed: 29
  split: [0.8, 0.1, 0.1]
  batch_size: 1
  lr: 1e-4

testing:
  load_path: 'models/best.pt'
  beam_search: false