model:
  num_encoders: 2
  num_decoders: 2

  d_model: 256
  num_heads: 8
  dropout: 0.1

training:
  epochs: 150
  save_path: 'model_2'
  load_path: ''

  num_frames: 30
  num_workers: 8
  seed: 29
  split: [0.8, 0.1, 0.1]
  batch_size: 8
  lr: 1e-3

testing:
  load_path: 'models/best.pt'
  beam_search: false