model:
  num_encoders: 2
  num_decoders: 2
  pretrained_embedding: "efficientnet_b0"

  d_model: 512
  num_heads: 8
  dropout: 0.1

training:
  # Basic hyperparameters
  epochs: 200
  batch_size: 8
  lr: 1e-3
  weight_decay: 1e-3
  save_every: 50
  validate_every: 3
    
  # File path locations
  save_path: 'models'
  file_name: 'best'
  load_path: ''
  diagram_path: ''
    
  # Weights used for joint loss
  recognition_weight: 1.0
  translation_weight: 1.0
  
  # Random splitting seed and ration
  seed: 29
  split: [0.8, 0.1, 0.1]

  # Early Stopping
  patience: 8
  delta: 0.01

  # Scheduler
  T_max: 50

  # Gradient clipping
  max_norm: 1.0
    
  # Misc.
  num_workers: 4

  # Dataset
  num_frames: 30
  sampling_ratio: 2
  masking_ratio: 0.8
  random_sampling: True
  random_masking: True
  

testing:
  load_path: 'models/test.pt'
  beam_search: false